Authentication Backend
aShahriarSazim/bcdg-demo pull request #2
Opened 2022-07-01 03:27 UTC by aShahriarSazim

I created the auth module and defined sign In sign Up functionalities. I also defined the passport-jwt strategy which I'll use later for authorization/middleware/guards

2022-07-01 13:08 UTC, rChowdhurySazim requested changes

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/auth.controller.ts
> +    @Post('/local/signin')
should be 'siginin'  only. applies for everywhere you used local.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/auth.controller.ts
> +        return this.AuthService.signUpLocal(dto);
remove local

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/auth.module.ts
> +export class AuthModule {}
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/dto/auth.dto.ts
> +}
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/dto/index.ts
> +export * from './auth.dto';
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/strategy/index.ts
> +export * from './jwt.strategy';
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/auth/strategy/jwt.strategy.ts
> +}
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/prisma/prisma.module.ts
> +export class PrismaModule {}
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 13:08 UTC, rChowdhurySazim commented on server/src/prisma/prisma.service.ts
> +}
Please add a newline at the end. Every file should have an empty newline at the end.

2022-07-01 14:47 UTC, aShahriarSazim commented on server/.env.example
> +JWT_SECRET="SOME RANDOM SECRET MAKE IT HARDER TO GUESS"
Done

2022-07-01 14:47 UTC, aShahriarSazim commented on server/src/auth/auth.controller.ts
> +    @Post('/local/signin')
Done

2022-07-01 14:47 UTC, aShahriarSazim commented on server/src/auth/auth.controller.ts
> +        return this.AuthService.signUpLocal(dto);
Done

2022-07-01 14:47 UTC, aShahriarSazim commented on server/src/auth/auth.module.ts
> +export class AuthModule {}
Done

2022-07-01 14:47 UTC, aShahriarSazim commented on server/src/auth/dto/auth.dto.ts
> +}
Done

2022-07-01 14:47 UTC, aShahriarSazim commented on server/src/auth/dto/index.ts
> +export * from './auth.dto';
Done

2022-07-01 14:47 UTC, aShahriarSazim commented on server/src/auth/strategy/index.ts
> +export * from './jwt.strategy';
Done

2022-07-01 14:48 UTC, aShahriarSazim commented on server/src/auth/strategy/jwt.strategy.ts
> +}
Done

2022-07-01 14:48 UTC, aShahriarSazim commented on server/src/prisma/prisma.module.ts
> +export class PrismaModule {}
Done

2022-07-01 15:14 UTC, rChowdhurySazim requested changes

2022-07-01 15:14 UTC, rChowdhurySazim commented on server/src/auth/auth.controller.ts
> +    async signInLocal(@Body() dto: signInDto) {
please remove local from the function name aswell

2022-07-01 15:14 UTC, rChowdhurySazim commented on server/src/auth/auth.controller.ts
> +    async signUpLocal(@Body() dto: signUpDto) {
please remove local from the function name aswell

2022-07-04 15:30 UTC, rChowdhurySazim approved these changes

2022-07-04 17:04 UTC, closed without merging