Product Frontend
aShahriarSazim/bcdg-demo pull request #7
Opened 2022-07-07 18:56 UTC by aShahriarSazim

Created Product CRUD frontend

2022-07-08 13:18 UTC, rChowdhurySazim requested changes
Please go through the comments and address them. One comment issue might be in multiple places, so address them everywhere.

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/store/slices/ProductSlice/ProductSlice.ts
> +const initialState : ProductInterface[]  = [];
You can make it an object with { allProduct : [], userProducts: [], etc.. } when you use createAsyncThunk from RTK

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/App.tsx
> +                <FetchAllProducts />
Should not do this. Fetch products in components where its necessary also should not use a whole component just for the fetching in useEffect.

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/components/FetchAllProducts.tsx
> +const FetchAllProducts: FC = () => {
- You need to use createAsyncThunk from RTK do all kind of api calls and manage the state in that slice
- Should not fetch all products with just one endpoint and do all operations on that data
- Need other endpoints like user/5/products or something to return the products owned by the user
- FetchAll should return the list of the products that are not owned by the user
- All kind of api calls should be in their respective files. There should not be a separate component just to use useEffect and state.

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/pages/Products/CreateProduct/CreateProduct.tsx
> +            // console.log(newProduct);
remove comment

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/pages/Products/CreateProduct/CreateProduct.tsx
> +            const response = await axios.post("/products/create", newProduct);
- You need to use createAsyncThunk from RTK do all kind of api calls and manage the state in that slice

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/pages/Products/EditProduct/EditProduct.tsx
> +            const response = await axios.post(`/products/update/${id}`, productToBeUpdated);
- You need to use createAsyncThunk from RTK do all kind of api calls and manage the state in that slice

2022-07-08 13:18 UTC, rChowdhurySazim commented on client/src/pages/Products/MyProducts/MyProducts.tsx
> +    );
- Need other endpoints like user/5/products or something to return the products owned by the user

2022-07-08 15:27 UTC, aShahriarSazim commented on client/src/pages/Products/components/Product.tsx
> +import {DeleteIcon} from "@chakra-ui/icons";
But view product page will have a few more functionalities (buy and rent) later

2022-07-14 11:16 UTC, aShahriarSazim commented on client/src/pages/Products/CreateProduct/CreateProduct.tsx
> +            temp.push(category.value);
done

2022-07-14 11:16 UTC, aShahriarSazim commented on client/src/pages/Products/CreateProduct/CreateProduct.tsx
> +    }, []);
removed unnecessary codes

2022-07-14 11:16 UTC, aShahriarSazim commented on client/src/pages/Products/Products.tsx
> +    }, []);
removed unnecessary codes

2022-07-14 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/ViewProduct/ViewProduct.tsx
> +    let product = useAppSelector(state => state.products.find(product => (product.id == parseInt(id))));
I haven't made those api endpoints yet, so I have to solve them in the next branch (should I make a new branch off of this product-FE branch and resolve them there and then merge?

2022-07-14 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/components/Product.tsx
> +import {DeleteIcon} from "@chakra-ui/icons";
changed the name to ProductCard

2022-07-14 11:18 UTC, aShahriarSazim commented on client/src/App.tsx
> +                <FetchAllProducts />
removed this

2022-07-18 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/ViewProduct/ViewProduct.tsx
> +    let product = useAppSelector(state => state.products.find(product => (product.id == parseInt(id))));
Resolved

2022-07-18 11:17 UTC, aShahriarSazim commented on client/src/components/FetchAllProducts.tsx
> +const FetchAllProducts: FC = () => {
Done

2022-07-18 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/CreateProduct/CreateProduct.tsx
> +            // console.log(newProduct);
Done

2022-07-18 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/CreateProduct/CreateProduct.tsx
> +            const response = await axios.post("/products/create", newProduct);
Done

2022-07-18 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/EditProduct/EditProduct.tsx
> +            const response = await axios.post(`/products/update/${id}`, productToBeUpdated);
Done

2022-07-18 11:17 UTC, aShahriarSazim commented on client/src/pages/Products/MyProducts/MyProducts.tsx
> +    );
Done

2022-07-20 17:21 UTC, rChowdhurySazim approved these changes

2022-07-21 03:50 UTC, merged